---
  header_logo_url: \images\flea_logo.png
  header_logo_text: Fleas of the World
  header_links:
    - label: Home
      link: /

#    - label: News
#      link: /news
    - label: Taxonomy
      link: /taxonomy

    - label: Morphology
      link: /

    - label: Search DwC
      link: /resources/tw/filter/dwc_otus

    - label: Bibliography
      link: /resources/tw/filter/bibliography
            
    - label: Flea collections
      link: /collections
    
    - label: Flea News
      link: /fleanews

    - label: About
      link: /about
