map_tiles:
   label: OpenStreetMap
   attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
   server: https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png
   zoomOffset: -1
   tileSize: 512
   minZoom: 1
   maxZoom: 18
   dpr:
   1: '@1x'
