taxa_page:
  overview:
    panels:
      - - - panel:gallery
          - panel:type
          - panel:type-specimen-v2
          - panel:nomenclature
          - panel:nomenclature-references

        - - panel:map-v2
          - panel:descendants
          - panel:content
          - panel:keys
          - panel:etymology
          - panel:gbif
          - panel:statistics

  asserted_distributions:
    panels:
     - - - panel:map-v2
     - - - panel:asserted-distributions
     
  specimen_records:
    rank_group: ['SpeciesGroup']
    panels:
      - - - panel:specimen-records
  
  biological_associations:
    panels:
      - - - panel:biological-associations-v2
      
  bibliography:
    panels:
      - - - panel:nomenclature-references